version: '3.8'

services:
  db:
    image: postgres:15-alpine
    
    container_name: postgres_sistema
    
    restart: always
    
    environment:
      POSTGRES_USER: admin_sistema
      POSTGRES_PASSWORD: "Ed00k@1234"
      POSTGRES_DB: Edook
    
    ports:
      - "5432:5432"
    
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: