spring.application.name=Edook

# informa aonde está o banco
spring.datasource.url=jdbc:postgresql://localhost:5433/Edook
# usuário do banco
spring.datasource.username=admin_sistema
# senha do usuário
spring.datasource.password=Ed00k@1234

# informa o que o Hibernate faz com as tabelas: criar, atualizar e deletar
spring.jpa.hibernate.ddl-auto=validate
# mostra as consultas que são executadas
spring.jpa.show-sql=true
# formata as consultas, fica mais facil de ver
spring.jpa.properties.hibernate.format_sql=true

# é um protocolo padrão de envio de emails
spring.mail.host=smtp.gmail.com
# porta utilizada pelo Gmail
spring.mail.port=587

# conta que enviará o email. Coloquei a minha so pra testar, mas deve ser alterado depois
spring.mail.username=corujadesirius@gmail.com
# senha de aplicativo gerada pelo gmail
spring.mail.password=hnfh phnn dunx qsuk

# ativa a autenticação exigindo o usuário e a senha
spring.mail.properties.mail.smtp.auth=true
# ativa a criptografia
spring.mail.properties.mail.smtp.starttls.enable=true

# indica quais ips podem acessar o servidor. 0.0.0.0 todos podem acessar
server.address=0.0.0.0
# porta
server.port=8080
app.base-url=http://localhost:8080
